---
title: "Analysis Resources"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
#### \   
# Setting Neuroscience Learning Outcomes 

If your local program does not have learning outcome goals developed already, [Chen and Phillips (2023)](https://www.lifescied.org/doi/full/10.1187/cbe.22-02-0018)\cite{Chen2023} published community-driven standards for neuroscience topics based on a nationwide survey of neuroscience educators.

Briefly, they define neuroscience's core concepts as the overarching principles that organize knowledge and can be applied to all subdisciplines in neuroscience. Those core concepts are:

1. __Communication modalities:__ Nervous systems encode and transmit information in various modalities that include activity patterns, electrical signaling, and chemical signaling. Information is transmitted and encoded in timing, frequency and patterns of activity.

2. __Emergence:__ Nervous system functions are constructed from the combined interactions of smaller constituent components. Complex functions such as cognition, behavior, perception, and emotion are the outcome of interactions between many smaller units at the tissue, cell, and sub-cellular levels.

3. __Evolution:__ Similarities and differences in nervous systems between organisms are constrained and defined by their evolutionary backgrounds. Evolutionary processes produce shared functions and homologous nervous system structures, as well as adaptations that generate differences between organisms. Nervous systems are subject to evolutionary forces and therefore must be understood within the phylogenetic history and ecological context of an organism.

4. __Gene–environment interactions:__ Unique patterns of gene expression underlie the organization and function of a nervous system and are altered by environmental factors.

5. __Information processing:__ Outputs from a unit in the nervous system depend on the inputs it receives as well as information filtering and modulation performed by the unit. Information processing can be studied at multiple levels of granularity, including synapses, subcellular arbors, circuits, and systems. At each level, the output of a unit in the nervous system is dependent upon the inputs it receives and processes.

6. __Nervous system functions:__ Nervous systems function to coordinate survival responses to the environment, permit behavior in a timely manner, and
maintain homeostatic regulation. Nervous systems detect and monitor external and internal environmental conditions, in conjunction with using stored information, to direct an appropriate response. 

7. __Plasticity:__ Nervous systems reorganize their structure, function, and connections in response to experience. The nervous system is malleable. From early developmental stages and throughout life, the nervous system strengthens and weakens components and connections in response to experience. This modulation, or plasticity, occurs in response to intrinsic and extrinsic experiences, such as sensory input, behavior, and pathological processes.

8. __Structure–function relationship:__ Structure permits and constrains nervous system function, and function shapes structure. Nervous system structures and functions bidirectionally inform each other at all levels of organization. 

#### \ 

# Setting Topic-Independent Learning Outcomes

The __Teaching Goals Inventory__, developed by Angelo and Cross (1993) is a good tool for identifying learning outcomes that are independent of course content and concepts knowledge goals. TGI was designed to: 

* help faculty choose informal classroom assessment methods; 
* help individual faculty members become aware of course goals; and 
* provide a starting point for discussion between colleagues. 

TGI also has proven extremely useful as a catalyst for new course development, and for analyzing connections between courses in a curricular sequence. The developers have given permission for the Inventory to be used freely, and it is [available online.](https://tgi.its.uiowa.edu/) 

#### \ 

# Other Resources for Supporting Analysis

## Examples of Learning Outcomes

[This article by Brownell, et al.](https://www.lifescied.org/doi/10.1187/cbe.13-12-0233)\cite{Brownell2014} and this 2023 article by [Clark and Hsu](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10074271/)\cite{Clark2023} are good overviews of the process.

These are two examples of program-level general learning outcomes. Individual courses within the programs would be designed to meet a subset of these outcomes.

* [Indiana University](https://biology.indiana.edu/undergraduate/biology/learning-goals.html)
* [Bates College](https://www.bates.edu/biology/biology-at-bates/learning-goals/)

#### \  

## Sources of Questions About Motivation and Interest

* [Rowland et al.'s 2019 literature review](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6755315/)\cite{Rowland2019}  of methods for defining and measuring student interest in biology.
* [Biology Self-Efficacy Scale](https://doi.org/10.1002/(SICI)1098-237X(199907)83:4%3C397::AID-SCE1%3E3.0.CO;2-%23)
* [Intrinsic Motivation Inventory, or IMI](https://selfdeterminationtheory.org/intrinsic-motivation-inventory/) 
* [Motivated Strategies for Learning Questionnaire, or MSLQ](https://psycnet.apa.org/doi/10.1037/0022-0663.82.1.33) 
* [The standard survey I use to gather data on student motivation and goals](downloads/Semester_startup_survey.md).

#### \  

<hr>
