---
title: "Brainstorming Ideas"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
#### \   

Before you start picking or writing cases, think about WHY you want to use them, and HOW you can best use them. The questions on this page will help you get started.

When you have a basic idea of what you want to accomplish with cases, read the overview of the [ADDIE model of curriculum design.](https://adanieljohnson.github.io/Case_Writing_Resources/curated_overview.html) Use the ADDIE model to refine your plan and start building your personal case set.

#### \   

# Case Goals

_What do you hope to accomplish or support with your teaching cases?_ 

The goals listed below are not comprehensive, just starting points to stimulate your thinking. 

* Within-Course Goals
    + Content & concepts mastery
        - Example: develop skills in R (or any specific knowledge domain) 
    + Basic disciplinary skills:
        - Ex. reading skills 
        - Ex. finding, summarizing reliable evidence 
        - Ex. interpreting data 
    + Applied thinking (aka, transfer) skills 
        - Ex. integrate and apply content to new situations 
        - Ex. evidence-based decision-making 
* Metacognitive Goals
    + Ex. taking ownership of learning 
    + Ex. team building/student cohesion
* Cross-Cutting Goals
    + Ex. collaborative problem solving 
    + Ex. project management skills
    + Ex. increased retention
* Professional Development
    + Ex. teacher & TA training
* ?
* ?

#### \   

# Implementation Barriers

_What implementation barriers or challenges do you expect to encounter, or would keep you from using cases?_

Again, the list below is just to stimulate your thinking.

* In-class challenges
    + Ex. freeloaders/social loafing
    + Ex. cheating, sharing across semesters
    + Ex. student discomfort with non-lecture format
    + Ex. how to provide constructive feedback 
* Challenges outside/beyond class time
    + Ex. do I know enough to write cases on topics outside of my expertise? 
    + Ex. students giving lower ratings on course evaluations
* ?
* ?

#### \   

# Case Formats

_What case format(s) would be most engaging, appropriate for your student population?_

There is no one "best" case format that works in all situations. For example, cases can be:

* Text vs. video based
* Historical/clinical vs. narrative stories
* Scenario- vs. data-centric 
* Other formats

Different case types and formats [are outlined here](https://adanieljohnson.github.io/case-writing-resources/FAQ.html). [Download this handout](https://adanieljohnson.github.io/case-writing-resources/downloads/NTC23_Case_Workshop_Handout_v1.docx) for more detailed descriptions. The [case collection](https://adanieljohnson.github.io/case-writing-resources/archive_overview.html) has examples of different case formats.

#### \   

<hr>