---
title: "Revising Your Cases"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
#### \   

I admit that I spend more time and energy tweaking cases than I should. It is easy to convince myself that I can "get it just right this time." 

> If I change "X" students will get to where I want them to go more easily. If I clarify "Y" they won't get as confused on Day 2. If I switch...

Over-editing can make your cases too easy, or add elements that break the flow. Make it a habit to NOT revise your cases until they truly need them.

#### \   

# When Should You Revise a Case?

I think the best time to make revisions is right after students have finished working through it. Problems with the case are fresher in your mind. You might want to wait to see how students perform on the next case or a linked case, or until you have additional evaluation data, but make revisions sooner rather than later. 

Avoid revising an existing case just before you give it to your students. Making __minor__ tweaks is a good way to refresh your memory of an upcoming case, but you can easily go to far if you do more. 

#### \   

# What Should You Revise?

These questions can help you identify what you might want to revise.

## Class Logistics

1. Is the case running as planned?
    + Does the case fit in the allotted time? 
    + Are students spending class time on task (discussing ideas, looking up information related to the case), or talking about non-class topics?
        - If students are not spending class time on topic, does the case need more content or a more in-depth assignment. 
        - Or, is the case too easy for most students?
    
2. If students get stuck, confused, or off track, do they need a little prompting to get back on track, or a lot?
    + I find that students learn a great deal from experiencing "positive confusion," that is, confusion that they overcome successfully. 
        - If students get back on track after one small prompt, they are experiencing positive confusion. 
        - If they remain lost, you may need to edit the guide questions to give clearer hints of the next logical step.

3. What questions are students asking repeatedly? 
    + Would additional specific information in the case materials answer the question without hurting the case flow?
    + Be careful not to over-compensate here and eliminate a point of positive confusion.

4. Are you getting the same questions about the case homework assignments from multiple students?
    + It is normal for students to have random questions about requirements.
    + If half of the students or groups ask essentially the same questions, the instructions for the assignments may be unclear.

5. Are submitted responses to the case assignments meeting your expectations?
    + If not, you may need to provide additional guidelines, or an example of what you expect.

6. What practical logistical challenges have shown up more than 1-2 times?
    + What are you (as the instructor) spending most of your time fixing or finding workarounds for?
    + What changes to the case would eliminate the workarounds?

## Learning Outcomes

7. Are students meeting all learning outcomes, some outcomes, or none?
    + Not every student will meet all goals, but all who participated fully should meet a majority of goals. 
    + If more than one goal was unmet, would meeting one particular goal help students meet the others? If so, that goal should be the priority in revision.

8. Can students apply what they learned from the case to new situations? Are students referring back to prior cases or class work when they answer the current case questions?
    + If not, what could you do as part of the case to develop transfer skills?
    + Students may not know how to call back prior work. Try adding a nudge question to the case that specifically asks them to make connections to a past case or class activity.

## Student Engagement

9. How did students respond to the case debrief?
    + Could they identify the main learning outcomes for the case? 
        - If not, consider adding that as a routine question to all case homework assignments.
    + What did students say they struggled with, or that you as the facilitator could have done to help?
        - You may need to provide more guidance on how to work as a team, or rearrange when you provide certain case information.
    + Did students find the case topic interesting? 
        - If not, you might consider reframing the introductory background to make the scenario more relevant to the students. 
        - Changing just the lead-in often improves student engagement with an unpopular case. 
    
#### \   
<hr>

# How Much Should You Revise a Case? 

I try to correct all of the basic mechanical issues in a case before I use it again. If there is no easy fix, I plan how to work around them more quickly next time. 
I am more cautious when making changes that affect learning outcomes or student engagement. One change can have unforeseen effects on how the case unfolds. Personally, I avoid changing more than 3 big features of a case at one time. 

For active cases I keep a running list of ideas for revision or improvement. Changes that I think will have the largest positive impact are at the top; those are what I change first. After using the revised case another time, I revisit the list, add new ideas, drop changes that are no longer relevent, and re-prioritize the list.

Most cases I revised this way have reached a stable form after 2-4 cycles. 

#### \   

# When Should You Retire a Case? 

A case that is not accomplishing your goals should be retired. For instance, I described above how I prioritize case revisions. If a case is not stable and working as I want by its fifth iteration, it probably needs to be retired and replaced with something else.  
It is harder to let go of a case that you wrote and enjoy, and that students like. Eventually they do age out. Signs that a case might need to be retired are:

* The central story is no longer topical, or the controversy the case explores has been resolved. 
    + A teaching rule of thumb is that undergraduates are unlikely to understand or care about any social or cultural reference more than 7 years old.
    + For example, it might be hard to imagine now in 2023, but most cases written about COVID-19 will be stale by 2030.
* The field has moved on.
    + In the early 2000s I read a case debating whether apex predators should have been reintroduced into Yellowstone Valley. Twenty years later, multiple studies have made the core debate moot.
    + The debate case structure itself is probably still usable; it just needs a new framing story.
* Students are less enthusiastic about the topic, or you as the facilitator do not enjoy leading students through the case.
    + If there is no emotional connection to the case, an essential affective element of learning is missing.

#### \   
<hr>
