---
title: "Toolbox"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
#### \   

Tools not described under one of the ADDIE categories or with broader uses are cataloged here. I also have listed some low/no cost tools and strategies that make case writing and use easier. 

#### \   

# Case Templates

## Minimal Case Template

Minimal case template files can be downloded in [Markdown format](downloads/Case-Template.md) or [MS Word format](downloads/Case-Template.docx).

#### \   

## 1-3-9 Branched Case Template

Several case authors have suggested a __branching case format__ that does not follow one storyline, but instead lets students follow different paths. Aside from the challenge of writing the content, there is the practical problem of managing students' access. 

__Twine__ could be the ideal platform for writing branched cases. It is an open-source application for writing interactive, non-linear stories. Twine creates one-page HTML documents divided into multiple sub-windows. Windows are connected together so viewers can read one window, then pick where they want to go next. 

* [Learn more about Twine here.](https://twinery.org/)
* [Download a working sample Twine web page here.](downloads/Twine_demo_template.html)
* [Download a template for a 1-3-9 Twine web page here.](downloads/Template_for_1-3-9_Case.html)

#### \   

# Markdown

Case documents often require multiple outputs: .docx files for printed handouts, .pdf for download-ready files, or .html for the campus LMS or the web generally. Managing documents can be difficult if you do not have a systematic strategy; mine is to draft most materials in **Markdown** then convert files. 

Markdown is a simple-to-use formatting language for authoring small, reusable plain text documents. The philosophy behind Markdown is "write text once, then output it in many formats." With Markdown authors can quickly convert one text file into more than 30 different formats for web pages, printed handouts, and slide presentations. Groups of Markdown files can be combined to create interactive online books. 

This entire web site was written in R Studio's variant, R Markdown. Several downloadable documents are written in plain Markdown (.md extension) or R Markdown (.Rmd extension). 

* The [page on Markdown conversion](markdown_conversion.html) describes how to convert files to other formats.
* To learn more about using Markdown and the R Markdown variant see [http://rmarkdown.rstudio.com](http://rmarkdown.rstudio.com).

#### \   

<hr>